services:
  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    volumes:
      - ./config:/config:rw
    networks:
      - web-secure
    ports:
      - 9091:9091
    labels:
      - 'traefik.enable=true'

      - 'traefik.http.routers.authelia-secure.rule=Host(`auth.apex-migrations.net`)'
      - 'traefik.http.routers.authelia-secure.entrypoints=web-secure'
      - 'traefik.http.routers.authelia-secure.tls=true'
      - 'traefik.http.routers.authelia-secure.tls.certresolver=production'

      - 'traefik.http.middlewares.authelia-secure.forwardauth.address=http://authelia:9091/api/verify?rd=https://auth.apex-migrations.net' # yamllint disable-line rule:line-length
      - 'traefik.http.middlewares.authelia-secure.forwardauth.trustForwardHeader=true'
      - 'traefik.http.middlewares.authelia-secure.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email' # yamllint disable-line rule:line-length

      - "traefik.http.routers.authelia-secure.middlewares=fail2ban@file"
      
    restart: unless-stopped
    healthcheck:
      disable: true
    environment:
      - TZ=Europe/Amsterdam

networks:
  web-secure:
    external: true
