---
###############################################################
#                   Authelia configuration                    #
###############################################################

jwt_secret: SEEEEH_BO_sa_kaba-bai_den_konyo-bo_mamaaaaa
default_redirection_url: https://auth.apex-migrations.net

server:
  host: 0.0.0.0
  port: 9091

log:
  level: debug
# This secret can also be set using the env variables AUTHELIA_JWT_SECRET_FILE

totp:
  issuer: authelia.com

# duo_api:
#  hostname: api-123456789.example.com
#  integration_key: ABCDEF
#  # This secret can also be set using the env variables AUTHELIA_DUO_API_SECRET_KEY_FILE
#  secret_key: 1234567890abcdefghifjkl

authentication_backend:
  file:
    path: /config/users_database.yml

access_control:
  default_policy: deny
  rules:
    - domain: traefik.apex-migrations.net # Traefik dashboard at home
      policy: one_factor
    - domain: traefik-azure.apex-migrations.net # Traefik dashboard in Azure
      policy: one_factor
    - domain: pihole.apex-migrations.net
      policy: one_factor
    - domain: portainer.apex-migrations.net
      policy: one_factor
    - domain: guacamole.apex-migrations.net
      policy: one_factor
    - domain: uptime.apex-migrations.net
      policy: one_factor
    - domain: matomo.apex-migrations.net
      policy: one_factor
    - domain: phpmyadmin.apex-migrations.net
      policy: one_factor
    - domain: dashboard.apex-migrations.net
      policy: one_factor
    - domain: grafana.apex-migrations.net
      policy: one_factor
    - domain: nextclouddb.gui.apex-migrations.net
      policy: one_factor
    - domain: router.apex-migrations.net
      policy: one_factor

session:
  name: authelia_session
  # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE
  secret: unsecure_session_secret
  expiration: 1h  # 1 hour
  same_site : lax
  inactivity: 30m  # 30 minutes. 5 minutes = 300
  remember_me_duration:  1w #1 week see: https://www.authelia.com/configuration/prologue/common/#duration-notation-format for notation
  domain: apex-migrations.net  # Should match whatever your root protected domain is

  # redis:
  #   host: redis
  #   port: 6379
  #   # This secret can also be set using the env variables AUTHELIA_SESSION_REDIS_PASSWORD_FILE
  #   # password: authelia

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  encryption_key: you_must_generate_a_random_string_of_more_than_twenty_chars_and_configure_this
  local:
    path: /config/db.sqlite3

notifier:
  # smtp:
  #   username: 2fa@apex-migrations.net
  #   # This secret can also be set using the env variables AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
  #   password: Laliloe4life
  #   host: smtp.transip.email
  #   port: 465
  #   sender: 2fa@apex-migrations.net
  filesystem:
    filename: /config/notification.txt
...