---
###############################################################
#                         Users Database                      #
###############################################################

# This file can be used if you do not have an LDAP set up.

# List of users
users:
  gcraane:
    displayname: "Gregory Craane"
    password: "$argon2id$v=19$m=65536,t=3,p=4$WEkxNVI2QTVhcHdpWURsbA$7FePpdNYczbj6JRnQIJOpsU4Hu/46+WtFMpAWDnoqoY"  # yamllint disable-line rule:line-length
    email: aquiles.craane@apex-migrations.net
    groups:
      - admins
      - dev

  a-grcr:
    displayname: "Gregory Craane | Referit"
    password: "$argon2id$v=19$m=65536,t=3,p=4$nqnOBgrRRHtmEie0IyZUPQ$nQ1xHLQTdjgj3Vx9qyMjKTQwgvFGB/Nkdglx7qHzjGI"  # yamllint disable-line rule:line-length
    email: gregory.craane@referit.nl
    groups:
      - admins
      - dev
...