---
###############################################################
#                         Users Database                      #
###############################################################

# This file can be used if you do not have an LDAP set up.

# List of users
users:
  gcraane:
    displayname: "Gregory Aquiles Craane"
    # Password is authelia
    password: "$argon2id$v=19$m=65536,t=3,p=4$WEkxNVI2QTVhcHdpWURsbA$7FePpdNYczbj6JRnQIJOpsU4Hu/46+WtFMpAWDnoqoY"  # yamllint disable-line rule:line-length
    email: aquiles.craane@cloud-migrations.nl
    groups:
      - admins
      - dev

  a-grcr:
    displayname: "Gregory Craane"
    # Password is authelia
    password: "$argon2id$v=19$m=65536,t=3,p=4,k=64$SEg4NGZpeERTRHhzS0tOMg$uveGIzfm89CESHEwYqeWsIrJQ+rze1Rs0aRTPfgq6ZzD/y/2MAB4vX3BKzlMrWb4VRlaVo9a9CKFz4YIhd3tEQ"  # yamllint disable-line rule:line-length
    email: gregory.craane@referit.nl
    groups:
      - admins
      - dev
...