######################################################
# This is a basic workflow to Deploy a traefik stack #
######################################################
name: Deploy Authelia

on:
  #################################################################
  # Allows you to run this workflow manually from the Actions tab #
  #################################################################
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run playbook
        uses: actions/checkout@v3
      - uses: dawidd6/action-ansible-playbook@v2
        name: Deploy Authelia 2FA
        with:
          playbook: /deployment.yml
          directory: ./deployments/roles/authelia-deployment
          key: ${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}
          inventory: |
            [all:vars]
            server17a_user=${{ secrets.USER }}
            vps_user=${{ secrets.VPS_USER }}
            server17a=${{ secrets.HOST }}
            vps=${{ secrets.VPS_HOST }}

            [all]
            server17a ansible_host={{ server17a }} ansible_port=${{ secrets.PORT }} ansible_user={{ server17a_user }}
            vps ansible_host={{ vps }} ansible_user={{ vps_user }}