######################################################
# This is a basic workflow to Deploy a traefik stack #
######################################################
name: Deploy Authelia

on:
  #################################################################
  # Allows you to run this workflow manually from the Actions tab #
  #################################################################
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run playbook
        uses: actions/checkout@v3
      - uses: dawidd6/action-ansible-playbook@v2
        name: Deploy Authelia 2FA
        with:
          playbook: main.yml
          directory: ./deployments/
          key: ${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}
          inventory: |
            [all]
            server17a ansible_host=${{ secrets.HOST }} ansible_port=${{ secrets.PORT }} ansible_user=${{ secrets.USER }}
            vps ansible_host=${{ secrets.VPS_HOST }} ansible_user=${{ secrets.VPS_USER }}